### PR TITLE
Logo for avatars

### PR DESCRIPTION
**Pull request by UsulPro**
issue: storybooks/storybook#1100

we updated our logo and I want to finish it with creating a new square and round versions
The only thing that confuses me and I'd like to confirm it before is the letter "S" outline. We still use the old style and it looks cool. But better if we have the same style both in avatars and logo.

So let's choose the one. 

`square.svg` has both variants in different layers

Don't merge!

### CODE REVIEW

**Comment by SachaG** [comment]
What about using https://github.com/storybooks/pres/blob/master/logo/v3/icon.png for avatars? It's square already.

**Comment by UsulPro** [comment]
is it intended to have white paddings around? 
Possible on small sizes it makes sense to occupy the entire space?

**Comment by SachaG** [comment]
Good point, we probably don't need the top and bottom padding.

**Comment by UsulPro** [comment]
Otherwise, it's the same style. Just inscribed in a square

**Comment by UsulPro** [comment]
And I made sure that the round looks the same as the square one. In fact, this is the same image, just with a mask

**Comment by SachaG** [comment]
https://github.com/storybooks/pres/commit/2d61f8402bda593eed2f356719fb106324c03f77

**Comment by SachaG** [comment]
I think that should work? I don't think we can use the images you submitted because they're too different from the main logo, sorry.

**Comment by UsulPro** [comment]
I don't mind. Just let's choose some option and use it everywhere.

**Comment by ndelangen** [comment]
Ready to merge?

**Comment by SachaG** [comment]
@ndelangen if you're talking about this PR, I don't think we should merge it? The icons are wrong.

**Comment by shilman** [comment]
Closing this, hope that's OK! 👍

**Pull request closed without merging**
